### ISSUE TITLE
Thin mint grenade toss crash

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#21]
```
(Thinman) Soldier X. Smith spotted!
(Thinman) Soldier F. Hinman spotted!
(Thinman) Warrior X. Lmao spotted!
(Thinman) Soldier X. Smith moves to Half cover!
(Thinman) Soldier F. Hinman moves to Full cover!
(Thinman) Warrior X. Lmao can't find any cover!

Rookie Green is out of AP!
HP: 2   AP: 13
Rookie Green is in FULL cover.
[1]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Soldier X. Smith - 5 HP - (60%)
[2]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Soldier F. Hinman - 5 HP - (40%)
[3]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Warrior X. Lmao - 7 HP - (90%)
[4]  (6 AP) Overwatch
[5]  (10 AP) (2 dmg) (10 AP) Use Frag Grenade
[6]  (3 AP) Reposition
[7]  (1 AP) Hunker down
[8] End turn
> 3
John Green: "AAGGHH!!!"
*Dakkadakkadakka*
2 damage!
HP: 2   AP: 7
Rookie Green is in FULL cover.
[1]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Soldier X. Smith - 5 HP - (60%)
[2]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Soldier F. Hinman - 5 HP - (40%)
[3]  (6 AP) (~3 dmg)(6AP) Fire Ballistic Rifle at (Thinman) Warrior X. Lmao - 5 HP - (90%)
[4]  (6 AP) Overwatch
[5]  (3 AP) Reposition
[6]  (1 AP) Hunker down
[7] End turn
> 3
John Green: "Take this!"
*Dakkadakkadakka*
 Missed!
HP: 2   AP: 1
Rookie Green is in FULL cover.
[1]  (1 AP) Hunker down
[2] End turn
> 1
John Green: "Taking cover!"
Rookie Green is out of AP!

--------------Alien Activity!--------------

(Thinman) Soldier X. Smith uses Alien Grenade!
**BLAM!**
3 damage!
Traceback (most recent call last):
  File "textcom.py", line 1756, in <module>
    alienTurn(soldier)
  File "textcom.py", line 1494, in alienTurn
    nade(alium)
  File "textcom.py", line 1447, in nade
    checkPlayerDead()
NameError: name 'checkPlayerDead' is not defined
voidref@AlSi ~/s/textcom> 
```

Just a guess, missing 'self.' ?

**Comment by TachyonNZ** [comment]
No, I think Flimberger just forgot to remove the checkplayerdead() call when they updated the structure. Fixed now.
