### ISSUE TITLE
Strange checkpoint crash

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#22]
```
> Peter Van Doorn: "Reached an access point, Commander. Requesting additional goods!"
Peter Van Doorn: "We only have a short time before the aliens close it off!"
Fragments: 28
Elerium: 23
Meld: 14
Alloy: 2
Time: 60
1: "Advance"
2: "(30 Time) (10m) (10f) Get Nano Serum"
3: "(20 Time) (5m) Recuperate (+1 HP)"
4: "(20 Time) Reload Weapon"
5: "(60 Time) Advance (Skip this Drop Zone)"
> 2
selected option 2
Nano Serum fabricated!
Fragments: 18
Elerium: 23
Meld: 4
Alloy: 2
Time: 40
1: "Advance"
2: "(20 Time) Reload Weapon"
3: "(40 Time) Advance (Skip this Drop Zone)"
> 2
selected option 2
Weapon reloaded!
Fragments: 18
Elerium: 23
Meld: 4
Alloy: 2
Time: 20
1: "Advance"
2: "(20 Time) Reload Weapon"
3: "(20 Time) Advance (Skip this Drop Zone)"
> 1
selected option 1
Peter Van Doorn: "All out of time! I'll have to keep moving!"
(Thinman) Soldier V. Clark spotted!
(Thinman) Soldier V. Clark moves to Half cover!

General Van Doorn is out of AP!
HP: 2   AP: 11
General Van Doorn is in FULL cover.
Traceback (most recent call last):
  File "textcom.py", line 1740, in <module>
    playerTurn()
  File "textcom.py", line 1348, in playerTurn
    if item.use_ap_costs > 0 and soldier.ap >= item.use_ap_costs:
AttributeError: 'int' object has no attribute 'use_ap_costs'
```

hooray for weak types and scripting languages!

**Comment by TachyonNZ** [comment]
Resolved, it was due to the shop appending an integer to the inventory instead of the medkit and frag grenade class.
