### ISSUE TITLE
AP miscalc on reload+advance

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#37]
```
(Sectoid) Guard Glarp Glop died!
HP: 5   AP: 8   Ammo: 0
Rookie Kerman is in FULL cover.
[a]  (1 AP) Advance
[r]  (8 AP) Reload
[d]  (9 AP) Reload + Advance
[e] End turn
> d
Traceback (most recent call last):
  File "textcom.py", line 1775, in <module>
    playerTurn()
  File "textcom.py", line 1390, in playerTurn
    prompt_player(actions).perform()
  File "textcom.py", line 1086, in perform
    advance_action.perform()
  File "textcom.py", line 996, in perform
    self._calc_ap()
  File "textcom.py", line 978, in _calc_ap
    format(self.name))
Exception: Not enough AP to perform action 'Advance'
```

**Comment by TachyonNZ** [comment]
Yeah, I found this.
