### ISSUE TITLE
I see that you have never beat this game ...

### ISSUE THREAD

**Issue by voidref** [TachyonNZ/textcom#40]
Index out of range exception when finishing.

```
Megan Fox: "Eat this!"
*W-W-Whap!*
5 damage!
(Muton) Uber Jeffery The Muton died!
Megan Fox: "Recovered a Nano-Serum!"
HP: 24  AP: 10  Ammo: 2
Colonel 'Seismic' Fox is in FULL cover.
[a]  (1 AP) Advance
[r]  (8 AP) Reload
[d] Reload + Advance
[e] End turn
> e
Colonel 'Seismic' Fox is out of AP!
HP: 24  AP: 19  Ammo: 2
Colonel 'Seismic' Fox is in FULL cover.
[a]  (1 AP) Advance
[r]  (8 AP) Reload
[d] Reload + Advance
[e] End turn
> d
Traceback (most recent call last):
  File "textcom.py", line 1830, in <module>
    playerTurn()
  File "textcom.py", line 1423, in playerTurn
    prompt_player(actions).perform()
  File "textcom.py", line 1118, in perform
    advance_action.perform()
  File "textcom.py", line 1030, in perform
    if not "Drop Zone" in room[roomNo]:
IndexError: list index out of range
```

**Comment by TachyonNZ** [comment]
Lol. You got me. Might be a naming thing.
